### ISSUE TITLE
Implementer Formulaire de consommation machine

### ISSUE THREAD

**Issue by Prefabloc** [Prefabloc/symfony_forms#42]
Permettre de connaitre la quantité d'essence qui a été mis dans un véhicule ou un engin

- [x] Une entité avec un label et un type permettant de differencier engin/vehicule

- [x] Formulaire et entité associé contenant la sélection d'un des véhicules en base ou engins + un champs consommation

**Comment by AmelieDucasse** [comment]
Voir pour la dynamisation avec le type de machine
